#!/usr/bin/env node
// Copies the signed-off design system from mockups/ into the interface asset tree.
//
// Constitution Principle I makes the mockup binding verbatim. Copying at build time means the
// only way the application can diverge is by editing the signed-off artifact — a visible,
// reviewable act. Hand-transcribing tokens would make drift silent, which is the failure the
// principle exists to prevent. An absent design system is therefore an error, never a
// degraded unstyled mode.
import { cp, mkdir, readdir, readFile, rm, writeFile, access } from 'node:fs/promises';
import { join } from 'node:path';

const MOCKUPS = 'mockups';
const DEST = 'src/lib/ds';

async function exists(p) {
  try {
    await access(p);
    return true;
  } catch {
    return false;
  }
}

async function findDesignSystem() {
  const dsRoot = join(MOCKUPS, '_ds');
  if (!(await exists(dsRoot))) {
    throw new Error(
      `No design system at ${dsRoot}. The signed-off mockup is required; refusing to build unstyled.`,
    );
  }
  const entries = await readdir(dsRoot, { withFileTypes: true });
  const bundle = entries.find((e) => e.isDirectory());
  if (!bundle) throw new Error(`No design system bundle inside ${dsRoot}.`);
  return join(dsRoot, bundle.name);
}

const bundle = await findDesignSystem();
const stylesheet = join(bundle, 'styles.css');
if (!(await exists(stylesheet))) {
  throw new Error(`Design system bundle at ${bundle} has no styles.css.`);
}

await rm(DEST, { recursive: true, force: true });
await mkdir(DEST, { recursive: true });
await cp(bundle, join(DEST, 'system'), { recursive: true });

for (const asset of ['fonts', 'icons']) {
  const src = join(MOCKUPS, asset);
  if (!(await exists(src))) throw new Error(`Missing ${src}; the design system requires it.`);
  await cp(src, join(DEST, asset), { recursive: true });
}

// ---------------------------------------------------------------------------
// Layout tokens (F018, FR-009).
//
// The prototype's layout dimensions are NOT in the design system stylesheet — that defines
// colour, spacing, radius, shadow and font tokens only. They live in the prototype's own
// markup, some as `var(--vk-*, <value>)` fallbacks and some as literals on specific
// elements.
//
// Editing the design system to add them would modify a signed-off artifact, which the
// design fidelity principle forbids. Hand-authoring them in application code would make the
// application the source of truth for a value the prototype owns. So they are extracted
// here, on every build, exactly as the design system itself is copied rather than
// transcribed: the only way to change one is to change the prototype.
//
// Written inside src/lib/ds/ deliberately — lint:ds skips that directory, and a token file
// necessarily contains the raw pixel values the lint forbids everywhere else.
const PROTOTYPE = join(MOCKUPS, 'Apex IDE (standalone).html');

// Each entry names a dimension and how to find it. Explicit rather than inferred: a reader
// can check any one of these against the prototype by eye.
const LAYOUT_TOKENS = [
  { token: '--vk-tool', re: /var\(--vk-tool,\s*(\d+(?:\.\d+)?px)\)/, what: 'tool window width' },
  { token: '--vk-dock', re: /var\(--vk-dock,\s*(\d+(?:\.\d+)?px)\)/, what: 'dock height' },
  { token: '--vk-row', re: /var\(--vk-row,\s*(\d+(?:\.\d+)?px)\)/, what: 'tree row height' },
  { token: '--vk-line', re: /var\(--vk-line,\s*(\d+(?:\.\d+)?px)\)/, what: 'editor line height' },
  { token: '--vk-code', re: /var\(--vk-code,\s*(\d+(?:\.\d+)?px)\)/, what: 'code font size' },
  { token: '--vk-fs', re: /var\(--vk-fs,\s*(\d+(?:\.\d+)?px)\)/, what: 'interface font size' },
  // Literals on identifiable elements rather than parameterised fallbacks.
  { token: '--vk-chrome-height', re: /data-screen-label=\\?"Chrome\\?"[^>]*?height:(\d+px)/, what: 'chrome header height' },
  { token: '--vk-rail-width', re: /<nav style=\\?"flex:none;width:(\d+px)/, what: 'activity rail width' },
];

const prototypeMarkup = await readFile(PROTOTYPE, 'utf8');
const extracted = [];
const missing = [];
for (const { token, re, what } of LAYOUT_TOKENS) {
  const m = re.exec(prototypeMarkup);
  if (m) extracted.push({ token, value: m[1], what });
  else missing.push(`${token} (${what})`);
}

if (missing.length > 0) {
  console.error('\nds:sync — layout dimensions not found in the prototype:');
  for (const m of missing) console.error(`  ${m}`);
  console.error(
    '\nThe prototype changed shape and the extraction no longer matches. Fix the pattern\n' +
      'rather than hard-coding the value: a hand-written dimension is exactly the drift the\n' +
      'design fidelity principle exists to prevent.',
  );
  process.exit(1);
}

const tokenCss = [
  '/* GENERATED by scripts/ds-sync.mjs from the signed-off prototype. Do not edit.',
  ' *',
  ' * These dimensions are not part of the design system stylesheet; they live in the',
  ' * prototype markup. Changing one means changing the prototype.',
  ' */',
  ':root {',
  ...extracted.map(({ token, value, what }) => `  ${token}: ${value}; /* ${what} */`),
  '}',
  '',
].join('\n');

await writeFile(join(DEST, 'layout-tokens.css'), tokenCss);

// ---------------------------------------------------------------------------
// FR-022: where the approved design does not cover a surface the feature needs, the gap is
// resolved with the designer before that surface is built. A component reaching for a token
// the design system never defined IS that gap, and it fails silently at runtime — the
// property just resolves to nothing and the element renders unstyled. This turns it into a
// build failure at the moment it is introduced.
import { readdir as readdirAsync, readFile as readFileAsync } from 'node:fs/promises';
import { extname } from 'node:path';

const stylesheetText = await readFile(join(DEST, 'system/styles.css'), 'utf8');
const defined = new Set([...stylesheetText.matchAll(/(--[a-z0-9-]+)\s*:/g)].map((m) => m[1]));

async function* sources(dir) {
  for (const e of await readdirAsync(dir, { withFileTypes: true })) {
    const full = join(dir, e.name);
    if (full.startsWith(DEST)) continue; // the system defines them; it does not consume them
    if (e.isDirectory()) yield* sources(full);
    else if (['.svelte', '.css', '.ts'].includes(extname(e.name))) yield full;
  }
}

const gaps = [];
for await (const file of sources('src')) {
  const text = await readFileAsync(file, 'utf8');
  text.split('\n').forEach((line, i) => {
    for (const m of line.matchAll(/var\(\s*(--[a-z0-9-]+)/g)) {
      if (!defined.has(m[1])) gaps.push(`${file}:${i + 1}  ${m[1]}`);
    }
  });
}

if (gaps.length > 0) {
  console.error('\nds:sync — components reference tokens the signed-off design does not define:');
  for (const g of gaps) console.error(`  ${g}`);
  console.error(
    '\nFR-022: resolve the gap with the designer and record the resolution before building\n' +
      'this surface. Do not improvise a value from an adjacent token.',
  );
  process.exit(1);
}

console.log(
  `ds:sync — copied ${bundle} plus fonts and icons into ${DEST}; ` +
    `${defined.size} design tokens, ${extracted.length} layout tokens extracted from the ` +
    `prototype, no undefined token references.`,
);
