#!/usr/bin/env node
// Approve a new fidelity baseline (FR-016).
//
// Deliberately a separate command. If the comparison refreshed the baseline whenever it
// failed, it would report success on every run and prove nothing — the approved design
// would silently become whatever was last built. Updating is an act someone performs and a
// reviewer sees in a diff.
//
// This writes only the baseline IMAGE. The expected geometry comes from the prototype and
// is regenerated by derive.mjs; no path here can quietly replace the prototype's numbers
// with our own output.
import { mkdir, copyFile, readFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { withShell, measureSurfaces, captureWindow, REFERENCE } from './measure.mjs';
import { SURFACES } from './derive.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, '../..');
const GEOMETRY = join(HERE, 'reference/geometry.json');
const BASELINE = join(HERE, 'reference/baseline-1200x800.png');
const STAGING = join(REPO, 'reports/fidelity/approved.png');

const POSITION_TOLERANCE_PX = 2;

async function main() {
  if (!existsSync(GEOMETRY)) {
    console.error(
      `gate:fidelity:update — the prototype-derived geometry is missing at ${GEOMETRY}.\n` +
        '  Derive it first: node tools/gate-fidelity/derive.mjs',
    );
    return 2;
  }
  const expected = JSON.parse(await readFile(GEOMETRY, 'utf8'));

  await mkdir(dirname(STAGING), { recursive: true });

  const actual = await withShell(async (browser) => {
    const surfaces = await measureSurfaces(browser, SURFACES);
    captureWindow(STAGING);
    return surfaces;
  });

  // Refuse to approve a rendering that does not match the prototype. Without this, the
  // update command would be a way to launder drift into an approved state — run the gate,
  // see it fail, update the baseline, see it pass, and the design is gone.
  const drift = [];
  for (const { name } of SURFACES) {
    const want = expected.surfaces?.[name];
    const got = actual[name];
    if (!want || !got) {
      drift.push(`${name}: missing from ${want ? 'the shell' : 'the reference geometry'}`);
      continue;
    }
    for (const axis of ['x', 'y', 'width', 'height']) {
      const delta = Math.abs(got[axis] - want[axis]);
      if (delta > POSITION_TOLERANCE_PX) {
        drift.push(`${name}: ${axis} is ${got[axis]}, the prototype has ${want[axis]}`);
      }
    }
  }

  if (drift.length > 0) {
    console.error('gate:fidelity:update — refusing to approve this rendering.\n');
    console.error('It does not match the prototype-derived geometry:');
    for (const d of drift) console.error(`  ${d}`);
    console.error(
      '\nFix the implementation, or — if the prototype itself changed — re-derive the\n' +
        'geometry from it first:  node tools/gate-fidelity/derive.mjs',
    );
    console.error(`\nThe rejected capture is at ${STAGING} if you want to look at it.`);
    return 1;
  }

  await copyFile(STAGING, BASELINE);
  console.log(
    `gate:fidelity:update — approved a new baseline at ${REFERENCE.width}x${REFERENCE.height}.\n` +
      `  ${BASELINE}\n` +
      '  Commit it: the approval is the review of that file.',
  );
  return 0;
}

process.exit(await main());
